"""RiskManager — tracks positions, P&L, and enforces every layer of risk limits.

Every order intent generated by the strategy must pass through `check()`
before being emitted.  If any limit would be violated, the order is
rejected with an explicit reason.

Design principle: failing closed.  When in doubt, reject.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from collections import defaultdict, deque
from time import time

from .config import RiskConfig
from .entities import (
    OrderIntent, PlaceQuote, CancelQuote, TakerOrder, FlattenInventory,
    MarketId, Position, Fill,
)


@dataclass
class RiskCheckResult:
    allowed: bool
    reason: str = ""


@dataclass
class SessionState:
    """Mutable session-level (daily) state."""
    start_pnl_usd: float = 0.0
    current_pnl_usd: float = 0.0
    peak_pnl_usd: float = 0.0
    n_consecutive_losses: int = 0
    halted_until_ts: float = 0.0
    n_taker_trades_last_hour: deque = field(default_factory=lambda: deque(maxlen=1000))
    n_trades_last_minute: deque = field(default_factory=lambda: deque(maxlen=1000))


class RiskManager:
    """Stateful position + loss tracker; gates every order intent."""

    def __init__(self, cfg: RiskConfig):
        self.cfg = cfg
        self.session = SessionState()
        self.positions: dict[MarketId, float] = defaultdict(float)
        self.avg_entry: dict[MarketId, float] = defaultdict(float)
        self.market_pnl: dict[MarketId, float] = defaultdict(float)
        self.consecutive_losses_per_market: dict[MarketId, int] = defaultdict(int)
        self.market_blackout_until: dict[MarketId, float] = defaultdict(float)
        self.active_quotes_count: int = 0

    # ── Position / P&L tracking (called by execution layer) ──────────────────

    def on_fill(self, fill: Fill) -> None:
        """Update internal state after a fill."""
        m = fill.market_id
        signed_size = fill.size if fill.order_side == "BID" else -fill.size

        # Update position with proper average-entry adjustment
        old_pos = self.positions[m]
        new_pos = old_pos + signed_size

        if abs(new_pos) < abs(old_pos):
            # Reducing position - realize P&L
            realized = (fill.price - self.avg_entry[m]) * (-signed_size)
            realized += fill.rebate_earned - fill.fees_paid
            self.market_pnl[m] += realized
            self.session.current_pnl_usd += realized
            self.session.peak_pnl_usd = max(self.session.peak_pnl_usd, self.session.current_pnl_usd)
            # Track consecutive losses
            if realized < 0:
                self.session.n_consecutive_losses += 1
                self.consecutive_losses_per_market[m] += 1
            else:
                self.session.n_consecutive_losses = 0
                self.consecutive_losses_per_market[m] = 0
        else:
            # Adding to or initiating position - update average
            if new_pos != 0:
                self.avg_entry[m] = (self.avg_entry[m] * old_pos + fill.price * signed_size) / new_pos
            # Fees/rebates still hit P&L immediately
            self.session.current_pnl_usd += (fill.rebate_earned - fill.fees_paid)

        self.positions[m] = new_pos

        # Trigger market blackout if too many consecutive losses
        if self.consecutive_losses_per_market[m] >= self.cfg.max_consecutive_losses_per_market:
            self.market_blackout_until[m] = time() + self.cfg.market_blackout_after_losses_seconds

        # Track trade rate
        self.session.n_trades_last_minute.append(time())

    def on_quote_placed(self) -> None:
        self.active_quotes_count += 1

    def on_quote_cancelled(self) -> None:
        self.active_quotes_count = max(0, self.active_quotes_count - 1)

    def on_taker(self) -> None:
        self.session.n_taker_trades_last_hour.append(time())

    # ── Pre-flight risk checks (called by strategy before emitting order) ────

    def check(self, intent: OrderIntent) -> RiskCheckResult:
        """Decide whether the given order intent passes all risk limits."""
        # Session-level halts
        if self._session_halted():
            return RiskCheckResult(False, "session halted")
        if self._daily_loss_breached():
            return RiskCheckResult(False, f"daily loss limit reached: {self.session.current_pnl_usd:.2f}")
        if self._drawdown_breached():
            return RiskCheckResult(False, f"drawdown limit reached")

        # Trade rate limits
        if self._too_many_trades_per_minute():
            return RiskCheckResult(False, "trades-per-minute cap reached")

        # Per-intent checks
        if isinstance(intent, PlaceQuote):
            return self._check_place_quote(intent)
        if isinstance(intent, CancelQuote):
            return RiskCheckResult(True)  # always allow cancels
        if isinstance(intent, TakerOrder):
            return self._check_taker(intent)
        if isinstance(intent, FlattenInventory):
            return RiskCheckResult(True)  # always allow defensive flatten
        return RiskCheckResult(False, "unknown intent type")

    # ── Internal predicates ──────────────────────────────────────────────────

    def _session_halted(self) -> bool:
        return time() < self.session.halted_until_ts

    def _daily_loss_breached(self) -> bool:
        return self.session.current_pnl_usd <= -self.cfg.max_daily_loss_usd

    def _drawdown_breached(self) -> bool:
        dd = self.session.peak_pnl_usd - self.session.current_pnl_usd
        return dd >= self.cfg.max_drawdown_from_session_peak_usd

    def _too_many_trades_per_minute(self) -> bool:
        now = time()
        # Drop stale
        while self.session.n_trades_last_minute and now - self.session.n_trades_last_minute[0] > 60:
            self.session.n_trades_last_minute.popleft()
        return len(self.session.n_trades_last_minute) >= self.cfg.max_trades_per_minute

    def _too_many_taker_per_hour(self) -> bool:
        now = time()
        while self.session.n_taker_trades_last_hour and now - self.session.n_taker_trades_last_hour[0] > 3600:
            self.session.n_taker_trades_last_hour.popleft()
        return len(self.session.n_taker_trades_last_hour) >= self.cfg.max_taker_trades_per_hour

    def _check_place_quote(self, q: PlaceQuote) -> RiskCheckResult:
        if q.size > self.cfg.max_size_per_quote_contracts:
            return RiskCheckResult(False, f"size {q.size} > per-quote cap {self.cfg.max_size_per_quote_contracts}")

        # Position would-be after fill check
        delta = q.size if q.order_side == "BID" else -q.size
        projected = self.positions[q.market_id] + delta
        if abs(projected) > self.cfg.max_position_per_market_contracts:
            return RiskCheckResult(False, f"projected pos {projected} > per-market cap")

        # Market blackout
        if time() < self.market_blackout_until[q.market_id]:
            return RiskCheckResult(False, f"market in blackout")

        # Global inventory
        gross = sum(abs(p) for p in self.positions.values()) + q.size
        if gross > self.cfg.max_gross_inventory_contracts:
            return RiskCheckResult(False, f"gross inventory {gross:.0f} > cap {self.cfg.max_gross_inventory_contracts}")

        # Active quotes
        if self.active_quotes_count >= self.cfg.max_active_quotes_total:
            return RiskCheckResult(False, f"too many active quotes ({self.active_quotes_count})")

        return RiskCheckResult(True)

    def _check_taker(self, t: TakerOrder) -> RiskCheckResult:
        if self._too_many_taker_per_hour():
            return RiskCheckResult(False, "taker rate limit reached")
        delta = t.size if t.order_side == "BID" else -t.size
        projected = self.positions[t.market_id] + delta
        if abs(projected) > self.cfg.max_position_per_market_contracts:
            return RiskCheckResult(False, f"taker would breach per-market position cap")
        return RiskCheckResult(True)

    # ── Position-sizing helpers (called by strategy when computing intent) ───

    def headroom_per_market(self, market_id: MarketId) -> float:
        return max(0.0, self.cfg.max_position_per_market_contracts - abs(self.positions[market_id]))

    def global_headroom(self) -> float:
        gross = sum(abs(p) for p in self.positions.values())
        return max(0.0, self.cfg.max_gross_inventory_contracts - gross)

    def position_for(self, market_id: MarketId) -> float:
        return self.positions[market_id]

    def session_summary(self) -> dict:
        return {
            "current_pnl_usd": self.session.current_pnl_usd,
            "peak_pnl_usd": self.session.peak_pnl_usd,
            "drawdown_usd": self.session.peak_pnl_usd - self.session.current_pnl_usd,
            "n_consecutive_losses": self.session.n_consecutive_losses,
            "n_active_quotes": self.active_quotes_count,
            "gross_inventory_contracts": sum(abs(p) for p in self.positions.values()),
            "n_open_positions": sum(1 for p in self.positions.values() if abs(p) > 1e-9),
        }
