#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Retrain orchestrator — produces and runs cleaned-feature variants of every
critical training script.

TWO MODES OF FIX (per script):

  A) FRAMEWORK MODE  - scripts that use model_factory's BaseTrainer:
       train_fair_resolution.py, train_fill_probability.py,
       train_adverse_selection.py, train_adverse_selection_to_close.py,
       train_closing_flip.py, train_mispricing.py,
       train_microstructure_direction.py
     For these, the cleanup is applied automatically via env-var hooks added to:
       - src/model_factory/dataset_loader.py  (FEATURE_CLEANUP_ENABLED=1)
       - src/model_factory/trainers/base_trainer.py  (MODEL_ARTIFACT_ROOT_OVERRIDE=artifacts_cleaned)
     We just set the env vars and invoke the original train_*.py — no patching.

  B) STANDALONE MODE - scripts that load data directly, bypassing model_factory:
       train_move_size_v2.py, train_maker_defense.py, train_maker_defense_v2.py,
       train_maker_defense_v3_eventtime.py
     For these we generate `train_*_cleaned.py` variants with:
       - clean_features() wrapping augment_btc_features
       - artifact paths rerouted to artifacts_cleaned/
       - BASE_FEATURES / ALL_FEATURES list translated via cleaned_feature_list

USAGE:
    # Generate the standalone _cleaned.py variants (no compute)
    py -3 retrain_all_cleaned.py --generate-only

    # Generate and run everything (framework scripts via env vars; standalone via _cleaned.py)
    py -3 retrain_all_cleaned.py --run --models critical

    # Run a single script for testing
    py -3 retrain_all_cleaned.py --run --models train_fair_resolution.py
"""
from __future__ import annotations
import io, sys, os, re, argparse, subprocess, time
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).parent

# ── Script classification ─────────────────────────────────────────────────────

FRAMEWORK_SCRIPTS = [
    # Run as-is with env vars: FEATURE_CLEANUP_ENABLED=1 + MODEL_ARTIFACT_ROOT_OVERRIDE=artifacts_cleaned
    "train_fair_resolution.py",
    "train_fill_probability.py",
    "train_adverse_selection.py",
    "train_adverse_selection_to_close.py",
    "train_closing_flip.py",
    "train_mispricing.py",
    "train_microstructure_direction.py",
]

STANDALONE_SCRIPTS = [
    # Use regex-patched _cleaned.py variants
    "train_move_size_v2.py",          # foundation — others import BASE_FEATURES from this
    "train_maker_defense.py",
    "train_maker_defense_v2.py",
    "train_maker_defense_v3_eventtime.py",
]

# Dependency order: standalone foundation first, then framework, then standalone-derived
CRITICAL_RUN_ORDER = [
    "train_move_size_v2.py",                        # standalone foundation
    "train_fair_resolution.py",                      # framework (cheap)
    "train_mispricing.py",                           # framework (cheap)
    "train_closing_flip.py",                         # framework (cheap)
    "train_microstructure_direction.py",             # framework
    "train_adverse_selection.py",                    # framework
    "train_adverse_selection_to_close.py",           # framework
    "train_fill_probability.py",                     # framework (biggest data)
    "train_maker_defense.py",                        # standalone
    "train_maker_defense_v2.py",                     # standalone
    "train_maker_defense_v3_eventtime.py",           # standalone (heaviest)
]

# Combined list used by --models critical
CRITICAL_SCRIPTS = CRITICAL_RUN_ORDER

# Env vars to inject for framework scripts
FRAMEWORK_ENV = {
    "FEATURE_CLEANUP_ENABLED": "1",
    "MODEL_ARTIFACT_ROOT_OVERRIDE": "artifacts_cleaned",
}

# ── Header injection for standalone scripts ──────────────────────────────────

HEADER_INJECTION = '''
# === FEATURE-CLEANUP PATCH (auto-generated by retrain_all_cleaned.py) ===
# This is a cleaned-feature variant of {orig_name}.
# Differences from the original:
#   - Trojan features (live_btc_usd, price_to_beat, live_applied_bias_age_seconds)
#     are dropped or transformed at training time via feature_cleanup.clean_features
#   - Feature lists are translated through feature_cleanup.cleaned_feature_list
#   - Artifacts are written to artifacts_cleaned/ instead of artifacts/
import sys as _sys
_sys.path.insert(0, "src")
from feature_cleanup import clean_features, cleaned_feature_list as _cfl, TROJAN_HARD as _TROJAN_HARD
# =====================================================================

'''


def patch_script(orig: Path, dest: Path) -> str:
    """Read orig training script, apply textual patches, write to dest.
    Used for STANDALONE scripts only (those that bypass model_factory).
    """
    src = orig.read_text(encoding="utf-8")
    edits = []

    # 1. Inject header after `from pathlib import Path`
    m = re.search(r"^(from pathlib import Path[^\n]*\n)", src, flags=re.MULTILINE)
    if m:
        ins_at = m.end()
        src = src[:ins_at] + HEADER_INJECTION.format(orig_name=orig.name) + src[ins_at:]
        edits.append("inject header after 'from pathlib import Path'")
    else:
        src = HEADER_INJECTION.format(orig_name=orig.name) + src
        edits.append("inject header at top")

    # 2. Reroute artifact paths: artifacts/ -> artifacts_cleaned/ (inside string literals)
    n_paths = 0
    def _reroute_path(m):
        nonlocal n_paths
        n_paths += 1
        return m.group(0).replace("artifacts/", "artifacts_cleaned/")
    src = re.sub(r'(["\'])artifacts/', _reroute_path, src)
    edits.append(f"reroute {n_paths} artifact path(s) -> artifacts_cleaned/")

    # 3. Hook augment_btc_features calls: wrap with clean_features
    n_aug = len(re.findall(r"\bdf\s*=\s*augment_btc_features\s*\(df\)", src))
    if n_aug:
        src = re.sub(
            r"\bdf\s*=\s*augment_btc_features\s*\(df\)",
            "df = clean_features(augment_btc_features(df))",
            src,
        )
        edits.append(f"wrap {n_aug} augment_btc_features() call(s) with clean_features()")

    # 4. For scripts without augment_btc_features (v3 eventtime), hook load_split return
    if n_aug == 0 and re.search(r"def load_split", src):
        src = re.sub(
            r"(def load_split\([^)]*\)\s*:[\s\S]*?)(\n\s+)(return df\s*$)",
            lambda m: m.group(1) + m.group(2) + "df = clean_features(df)" + m.group(2) + m.group(3),
            src, count=1, flags=re.MULTILINE,
        )
        edits.append("inject clean_features(df) into load_split() return path")

    # 5. Override every module-level *_FEATURES list we can find.
    # Build the override dynamically by scanning the source for assignments
    # of the form `NAME_FEATURES = ...` at module level.
    found_lists = sorted(set(re.findall(r"^([A-Z][A-Z0-9_]*FEATURES[A-Z0-9_]*)\s*=", src, flags=re.MULTILINE)))
    if not found_lists:
        found_lists = ["BASE_FEATURES", "AGG_FEATURES", "ALL_FEATURES"]
    override_lines = ["", "# === FEATURE LIST OVERRIDE (auto-generated) ==="]
    for name in found_lists:
        override_lines.append(f"try:\n    {name} = _cfl({name}, include_bucket=False)\nexcept NameError:\n    pass")
    override_lines.append("# ==============================================")
    feature_override = "\n".join(override_lines) + "\n"
    m = re.search(r"^def\s+\w+\s*\(", src, flags=re.MULTILINE)
    if m:
        src = src[:m.start()] + feature_override + "\n" + src[m.start():]
        edits.append("inject feature-list override before first def")
    else:
        src = src + feature_override
        edits.append("append feature-list override at end")

    dest.write_text(src, encoding="utf-8")
    return "; ".join(edits)


def generate_standalone_variants(scripts: list[str]) -> dict[str, str]:
    """Generate _cleaned.py variants for the standalone scripts in the list."""
    results = {}
    for name in scripts:
        if name not in STANDALONE_SCRIPTS:
            continue
        orig = ROOT / name
        if not orig.exists():
            print(f"  SKIP missing {name}", file=sys.stderr)
            results[name] = "missing"
            continue
        dest = ROOT / name.replace(".py", "_cleaned.py")
        summary = patch_script(orig, dest)
        print(f"  {name} -> {dest.name}", file=sys.stderr)
        print(f"    edits: {summary}", file=sys.stderr)
        results[name] = summary
    return results


def run_one(script: str, extra_args: list[str]) -> tuple[int, float]:
    """Invoke a training script appropriately based on its classification."""
    if script in FRAMEWORK_SCRIPTS:
        # Run original with env vars
        target = ROOT / script
        env = {**os.environ, **FRAMEWORK_ENV}
        label = f"{target.name}  [FRAMEWORK, env vars set]"
    elif script in STANDALONE_SCRIPTS:
        # Run _cleaned.py variant
        target = ROOT / script.replace(".py", "_cleaned.py")
        env = os.environ.copy()
        label = f"{target.name}  [STANDALONE]"
    else:
        print(f"  SKIP unknown script class: {script}", file=sys.stderr)
        return -1, 0.0

    if not target.exists():
        print(f"  SKIP target not found: {target.name}", file=sys.stderr)
        return -1, 0.0

    print(f"\n[RETRAIN] {label} {' '.join(extra_args)}", file=sys.stderr)
    t0 = time.time()
    rc = subprocess.call(
        [sys.executable, "-W", "ignore", str(target), *extra_args],
        cwd=str(ROOT),
        env=env,
    )
    dt = time.time() - t0
    print(f"[RETRAIN] {target.name} done in {dt:.0f}s (exit {rc})", file=sys.stderr)
    return rc, dt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--generate-only", action="store_true",
                    help="Generate _cleaned.py variants for standalone scripts; do not run.")
    ap.add_argument("--run", action="store_true",
                    help="Generate (if needed) AND run each script in sequence.")
    ap.add_argument("--models", nargs="*", default=["critical"],
                    help="Which scripts: 'critical' or specific filenames.")
    ap.add_argument("--train-args", nargs="*", default=[],
                    help="Extra args passed through to each training script.")
    args = ap.parse_args()

    if args.models == ["critical"]:
        scripts = CRITICAL_RUN_ORDER
    else:
        scripts = args.models

    print(f"Mode: {'generate+run' if args.run else 'generate-only'}", file=sys.stderr)
    print(f"Scripts ({len(scripts)}):", file=sys.stderr)
    for s in scripts:
        cls = "FRAMEWORK" if s in FRAMEWORK_SCRIPTS else "STANDALONE" if s in STANDALONE_SCRIPTS else "UNKNOWN"
        print(f"  - {s}  [{cls}]", file=sys.stderr)

    print("\n[STEP 1] Generating cleaned variants for standalone scripts...", file=sys.stderr)
    standalone_needed = [s for s in scripts if s in STANDALONE_SCRIPTS]
    if standalone_needed:
        generate_standalone_variants(standalone_needed)
    else:
        print("  (no standalone scripts in this run)", file=sys.stderr)

    framework_in_run = [s for s in scripts if s in FRAMEWORK_SCRIPTS]
    if framework_in_run:
        print(f"\n[STEP 1b] {len(framework_in_run)} framework script(s) will run with env vars:", file=sys.stderr)
        for k, v in FRAMEWORK_ENV.items():
            print(f"    {k}={v}", file=sys.stderr)

    if args.generate_only:
        print("\n--generate-only set; not running.", file=sys.stderr)
        print("\nNext steps:", file=sys.stderr)
        print("  Run all: py -3 retrain_all_cleaned.py --run --models critical", file=sys.stderr)
        return

    if not args.run:
        print("\nNothing to do (need --run or --generate-only).", file=sys.stderr)
        return

    print("\n[STEP 2] Running training scripts...", file=sys.stderr)
    summary = []
    for s in scripts:
        rc, dt = run_one(s, args.train_args)
        summary.append((s, rc, dt))

    print("\n" + "=" * 80, file=sys.stderr)
    print("RETRAIN SUMMARY", file=sys.stderr)
    print("=" * 80, file=sys.stderr)
    total = 0.0
    for s, rc, dt in summary:
        flag = "OK" if rc == 0 else f"FAIL({rc})"
        print(f"  {flag:>8}  {s:<45}  {dt:>6.0f}s", file=sys.stderr)
        total += dt
    print(f"\nTotal elapsed: {total:.0f}s ({total/60:.1f} min)", file=sys.stderr)
    n_fail = sum(1 for _, rc, _ in summary if rc != 0)
    if n_fail:
        print(f"\n{n_fail} script(s) failed. Investigate before deploying any cleaned artifacts.", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
