"""Maker-Defense Classifier (Model 8c): dramatic-move early-warning.

Use case: hybrid maker/taker bot. In MAKER state, resting limit orders get
filled at stale prices if the market suddenly jumps 0.10+ in 5 seconds.
The cost of one missed dramatic move (catastrophic adverse fill) far
exceeds the cost of many false alarms (briefly withdraw makers, lose
some fee rebate).

Asymmetric objective:
  - Recall on dramatic moves >= 0.95 (we MUST catch them)
  - FPR can be 10-30% (acceptable: pull makers, requote shortly)
  - Precision is secondary

Targets trained:
  A) big_move_010_5s:  |mid_move_5s|  >= 0.10  (primary maker defense)
  B) big_move_007_3s:  |mid_move_3s|  >= 0.07  (earlier warning, faster horizon)
  C) big_move_005_5s:  |mid_move_5s|  >= 0.05  (precursor signal, more data)

Class imbalance handled via:
  - scale_pos_weight tuned per target
  - threshold sweep with recall@FPR analysis
  - early stopping on val log-loss

Leakage guard: all `mid_move_*` future columns are EXCLUDED from features.
"""
import sys, json, os
os.environ["PYTHONIOENCODING"] = "utf-8"
from pathlib import Path

# === FEATURE-CLEANUP PATCH (auto-generated by retrain_all_cleaned.py) ===
# This is a cleaned-feature variant of train_maker_defense.py.
# Differences from the original:
#   - Trojan features (live_btc_usd, price_to_beat, live_applied_bias_age_seconds)
#     are dropped or transformed at training time via feature_cleanup.clean_features
#   - Feature lists are translated through feature_cleanup.cleaned_feature_list
#   - Artifacts are written to artifacts_cleaned/ instead of artifacts/
import sys as _sys
_sys.path.insert(0, "src")
from feature_cleanup import clean_features, cleaned_feature_list as _cfl, TROJAN_HARD as _TROJAN_HARD
# =====================================================================


sys.path.insert(0, "src")

import numpy as np
import polars as pl
import lightgbm as lgb
import joblib
from sklearn.metrics import (
    roc_auc_score, average_precision_score, precision_recall_curve,
    roc_curve, log_loss,
)

from model_factory.trainers.logistic_regression_trainer import _to_float_array
from train_move_size_v2 import (
    augment_btc_features, BASE_FEATURES, DERIVED_FEATURES, ALL_FEATURES,
    TRAIN_DATES, VAL_DATES, TEST_DATES,
)


DATASET_PATH = Path("data/datasets/microstructure_sequence_dataset_v1_tabular")


# Three defense targets, increasing horizon sensitivity
TARGETS = [
    {"name": "extreme_10c_5s",  "move_col": "mid_move_5s",  "threshold": 0.10},
    {"name": "severe_7c_3s",    "move_col": "mid_move_3s",  "threshold": 0.07},
    {"name": "moderate_5c_5s",  "move_col": "mid_move_5s",  "threshold": 0.05},
]


# ---------------------------------------------------------------------------
# Data loading -- needs move cols for all horizons we target
# ---------------------------------------------------------------------------

LOAD_COLS_FULL = list(dict.fromkeys(
    BASE_FEATURES + [
        "market_slug", "token_side_normalized", "anchor_ts_ns",
        "mid_move_5s", "mid_move_3s", "mid_move_1s",
        "sequence_feature_eligible",
    ]
))




# === FEATURE LIST OVERRIDE (auto-generated) ===
try:
    BASE_FEATURES = _cfl(BASE_FEATURES, include_bucket=False)
except NameError:
    pass
try:
    AGG_FEATURES = _cfl(AGG_FEATURES, include_bucket=False)
except NameError:
    pass
try:
    ALL_FEATURES = _cfl(ALL_FEATURES, include_bucket=False)
except NameError:
    pass
# ==============================================

def load_split(dates, split_name):
    print(f"  [{split_name}] Loading {len(dates)} day(s)...", flush=True)
    frames = []
    for d in dates:
        f = DATASET_PATH / f"{d}.parquet"
        if not f.exists():
            print(f"    SKIP missing: {d}")
            continue
        schema = pl.scan_parquet(str(f)).collect_schema()
        avail = set(schema.names())
        cols = [c for c in LOAD_COLS_FULL if c in avail]
        frames.append(pl.read_parquet(str(f), columns=cols))
    df = pl.concat(frames, how="vertical_relaxed")

    if "sequence_feature_eligible" in df.columns:
        df = df.filter(pl.col("sequence_feature_eligible"))

    # Filter NaN target rows (any of the move columns; we keep rows where at
    # least one of the targets is computable)
    df = df.filter(
        pl.col("mid_move_5s").is_not_null() & pl.col("mid_move_5s").is_not_nan()
    )

    print(f"  [{split_name}] {df.height:,} rows after eligibility filter")

    df = clean_features(augment_btc_features(df))

    # Create all targets
    for t in TARGETS:
        df = df.with_columns(
            (pl.col(t["move_col"]).abs() >= t["threshold"]).cast(pl.Int8).alias(f"target_{t['name']}")
        )
        pos = float(df[f"target_{t['name']}"].mean())
        print(f"  [{split_name}] target {t['name']}: positive_rate={pos:.4%}")
    return df


# ---------------------------------------------------------------------------
# Recall @ FPR analysis (the key metric for maker defense)
# ---------------------------------------------------------------------------

def recall_at_fpr(y_true, y_score, target_fprs=(0.05, 0.10, 0.15, 0.20, 0.30)):
    """For each target FPR, find threshold and report achieved recall."""
    fpr, tpr, thresholds = roc_curve(y_true, y_score)
    out = []
    for target in target_fprs:
        # Find the highest threshold where fpr <= target
        idx = np.searchsorted(fpr, target, side="right") - 1
        idx = max(0, min(idx, len(thresholds) - 1))
        out.append({
            "target_fpr": target,
            "achieved_fpr": float(fpr[idx]),
            "recall": float(tpr[idx]),
            "threshold": float(thresholds[idx]),
        })
    return out


def fpr_at_recall(y_true, y_score, target_recalls=(0.90, 0.95, 0.98, 0.99)):
    """For each target recall, find threshold and report FPR."""
    fpr, tpr, thresholds = roc_curve(y_true, y_score)
    out = []
    for target in target_recalls:
        # Lowest threshold where recall >= target
        idx = np.searchsorted(tpr, target, side="left")
        idx = max(0, min(idx, len(thresholds) - 1))
        out.append({
            "target_recall": target,
            "achieved_recall": float(tpr[idx]),
            "fpr": float(fpr[idx]),
            "threshold": float(thresholds[idx]),
        })
    return out


# ---------------------------------------------------------------------------
# Train one target
# ---------------------------------------------------------------------------

def train_target(target_cfg, train_df, val_df, test_df):
    name = target_cfg["name"]
    print(f"\n{'='*72}")
    print(f"  TRAINING: {name}  |  target = |{target_cfg['move_col']}| >= {target_cfg['threshold']}")
    print(f"{'='*72}")

    X_train, _ = _to_float_array(train_df.select(ALL_FEATURES))
    y_train = train_df[f"target_{name}"].to_numpy().astype(int)
    X_val, _ = _to_float_array(val_df.select(ALL_FEATURES))
    y_val = val_df[f"target_{name}"].to_numpy().astype(int)
    X_test, _ = _to_float_array(test_df.select(ALL_FEATURES))
    y_test = test_df[f"target_{name}"].to_numpy().astype(int)

    print(f"  pos rates: train={y_train.mean():.4%}  val={y_val.mean():.4%}  test={y_test.mean():.4%}")
    print(f"  positives: train={y_train.sum():,}  val={y_val.sum():,}  test={y_test.sum():,}")

    # NOTE: scale_pos_weight intentionally NOT used.  With severe imbalance
    # (1% positives) it produces extreme predictions whose val log-loss is
    # worst at iter 1, killing early stopping.  Instead we leave the model
    # to learn natural probabilities and tune the threshold downstream.
    # Optimization metric set to AUC since it is invariant to base rate.
    model = lgb.LGBMClassifier(
        objective="binary",
        metric="auc",
        num_leaves=63,
        min_child_samples=200,
        learning_rate=0.05,
        n_estimators=1500,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        random_state=42,
        verbose=-1,
        n_jobs=-1,
    )
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric="auc",
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)],
    )
    print(f"  best_iteration: {model.best_iteration_}")

    # Eval
    proba_val  = model.predict_proba(X_val)[:, 1]
    proba_test = model.predict_proba(X_test)[:, 1]

    auc_val   = roc_auc_score(y_val,  proba_val)
    auc_test  = roc_auc_score(y_test, proba_test)
    ap_val    = average_precision_score(y_val,  proba_val)
    ap_test   = average_precision_score(y_test, proba_test)
    base_test = float(y_test.mean())

    print(f"\n  [VAL]  AUC={auc_val:.4f}  AvgPrec={ap_val:.4f}  base_rate={y_val.mean():.4%}")
    print(f"  [TEST] AUC={auc_test:.4f}  AvgPrec={ap_test:.4f}  base_rate={base_test:.4%}")
    print(f"  TEST lift over random: {ap_test / base_test:.2f}x")

    print("\n  --- TEST: FPR @ target Recall (maker defense lens) ---")
    print(f"  {'Target Recall':>14s}  {'Achieved':>10s}  {'FPR':>8s}  {'Threshold':>10s}  {'%selected':>10s}")
    print(f"  {'-'*14}  {'-'*10}  {'-'*8}  {'-'*10}  {'-'*10}")
    fpr_table = fpr_at_recall(y_test, proba_test, target_recalls=(0.80, 0.90, 0.95, 0.98, 0.99))
    for row in fpr_table:
        sel_pct = float((proba_test >= row["threshold"]).mean())
        print(f"  {row['target_recall']:>14.2%}  {row['achieved_recall']:>10.4f}  "
              f"{row['fpr']:>8.4f}  {row['threshold']:>10.4f}  {sel_pct:>10.2%}")

    print("\n  --- TEST: Recall @ target FPR ---")
    print(f"  {'Target FPR':>10s}  {'Achieved':>10s}  {'Recall':>8s}  {'Threshold':>10s}  {'%selected':>10s}")
    print(f"  {'-'*10}  {'-'*10}  {'-'*8}  {'-'*10}  {'-'*10}")
    rec_table = recall_at_fpr(y_test, proba_test, target_fprs=(0.05, 0.10, 0.15, 0.20, 0.30))
    for row in rec_table:
        sel_pct = float((proba_test >= row["threshold"]).mean())
        print(f"  {row['target_fpr']:>10.2%}  {row['achieved_fpr']:>10.4f}  "
              f"{row['recall']:>8.4f}  {row['threshold']:>10.4f}  {sel_pct:>10.2%}")

    # Top features
    print("\n  --- Top 10 features ---")
    imp = sorted(zip(ALL_FEATURES, model.feature_importances_), key=lambda x: -x[1])[:10]
    total = float(model.feature_importances_.sum()) or 1.0
    for n, v in imp:
        print(f"    {v/total:.4f}  {n}")

    return {
        "target": name,
        "definition": f"|{target_cfg['move_col']}| >= {target_cfg['threshold']}",
        "pos_rate_test": base_test,
        "auc_val": float(auc_val),
        "auc_test": float(auc_test),
        "ap_val": float(ap_val),
        "ap_test": float(ap_test),
        "lift_over_random": float(ap_test / base_test),
        "fpr_at_recall": fpr_table,
        "recall_at_fpr": rec_table,
        "best_iter": int(model.best_iteration_ or 0),
        "feature_importance": {n: float(v/total) for n, v in zip(ALL_FEATURES, model.feature_importances_)},
    }, model


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("\n" + "#"*72)
    print("  MAKER-DEFENSE CLASSIFIER (Model 8c)")
    print("  Asymmetric objective: maximize recall on dramatic moves")
    print("#"*72)

    print("\n--- Loading data ---")
    train_df = load_split(TRAIN_DATES, "train")
    val_df   = load_split(VAL_DATES,   "val")
    test_df  = load_split(TEST_DATES,  "test")

    out_root = Path("artifacts_cleaned/model_08c_maker_defense")
    out_root.mkdir(parents=True, exist_ok=True)

    all_results = {}
    for tgt in TARGETS:
        metrics, model = train_target(tgt, train_df, val_df, test_df)
        all_results[tgt["name"]] = metrics
        save_dir = out_root / tgt["name"]
        save_dir.mkdir(parents=True, exist_ok=True)
        joblib.dump(model, save_dir / "model.pkl")
        with open(save_dir / "metrics.json", "w", encoding="utf-8") as f:
            json.dump(metrics, f, indent=2)
        print(f"\n  saved to {save_dir}")

    # Save consolidated
    with open(out_root / "all_results.json", "w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2)

    print("\n\n" + "#"*72)
    print("  SUMMARY: MAKER-DEFENSE READINESS")
    print("#"*72)
    print(f"\n  {'Target':<22s}  {'pos_rate':>9s}  {'AUC':>6s}  {'AP':>6s}  "
          f"{'FPR@95%rec':>11s}  {'FPR@99%rec':>11s}")
    print(f"  {'-'*22}  {'-'*9}  {'-'*6}  {'-'*6}  {'-'*11}  {'-'*11}")
    for name, m in all_results.items():
        f95 = next((r["fpr"] for r in m["fpr_at_recall"] if r["target_recall"] == 0.95), float("nan"))
        f99 = next((r["fpr"] for r in m["fpr_at_recall"] if r["target_recall"] == 0.99), float("nan"))
        print(f"  {name:<22s}  {m['pos_rate_test']:>9.4%}  "
              f"{m['auc_test']:>6.4f}  {m['ap_test']:>6.4f}  "
              f"{f95:>10.4f}  {f99:>10.4f}")

    print("\n  Interpretation:")
    print("  - FPR@95%rec = false positive rate when we catch 95% of dramatic moves")
    print("  - FPR@99%rec = false positive rate when we catch 99% of dramatic moves")
    print("  - Lower FPR = fewer unnecessary maker withdrawals")
    print()
    print("=== DONE ===")
