"""Regenerate the script indexes for `tools/` and `research/`.

Each entry is the first line of the script's module docstring, so the index
cannot drift from the code: fix the docstring and re-run.

Usage:
    py tools/generate_script_index.py
"""
from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Prefix -> section heading. Order matters: first match wins.
TOOL_SECTIONS: list[tuple[str, tuple[str, ...]]] = [
    ("Dataset construction", ("build_", "make_", "augment_", "cache_")),
    ("Backtesting and replay", ("backtest_", "replay_", "score_", "eval_", "calib")),
    ("Audits and verification", ("audit_", "verify_", "validate_", "check_", "diag_", "diagnose_")),
    ("Policy search and selection", ("search_", "deep_search_", "drilldown_", "compare_")),
    ("Analysis and diagnostics", ("analyze_", "collect_", "compute_", "diff_", "dump_", "feature_")),
    ("Operations", ("canonical_daemon", "nightly_", "run_", "shard_", "bootstrap_", "experiment_")),
]

RESEARCH_DIRS = {
    "training": (
        "Model training",
        (
            "Per-model training entry points from the supervised phase (Models 01-08c). "
            "`*_cleaned.py` variants retrain on the leakage-audited feature set."
        ),
    ),
    "evaluation": (
        "Evaluation and audits",
        "Out-of-sample evaluations, leakage/trojan audits, and phase-level analyses.",
    ),
    "exploratory": (
        "Exploratory analysis",
        (
            "Single-question scripts written to settle one point and kept for provenance. "
            "These are working notes in code form, not maintained interfaces."
        ),
    ),
    "pipeline": (
        "Pipeline utilities",
        "Feature builders, monitors and orchestration helpers from the same phase.",
    ),
}


def summary(path: Path) -> str:
    """First line of the module docstring, or the first real comment."""
    text = path.read_text(encoding="utf-8", errors="replace")
    try:
        doc = ast.get_docstring(ast.parse(text))
    except SyntaxError:
        doc = None
    if doc and doc.strip():
        return doc.strip().splitlines()[0].strip()
    for line in text.splitlines()[:15]:
        stripped = line.strip()
        if stripped.startswith("#") and not stripped.startswith("#!") and len(stripped) > 3:
            return stripped.lstrip("# ").strip()
    return ""


def section_for(name: str) -> str:
    for heading, prefixes in TOOL_SECTIONS:
        if name.startswith(prefixes):
            return heading
    return "Other"


def write_tools_index() -> None:
    scripts = sorted(p for p in (ROOT / "tools").glob("*.py") if p.name != Path(__file__).name)
    grouped: dict[str, list[Path]] = {}
    for path in scripts:
        grouped.setdefault(section_for(path.name), []).append(path)

    order = [heading for heading, _ in TOOL_SECTIONS] + ["Other"]
    lines = [
        "# Tools",
        "",
        f"{len(scripts)} research scripts. Each is runnable standalone with `py tools/<name>.py`;",
        "most accept `--help`. Descriptions come from each script's docstring and are",
        "regenerated by `tools/generate_script_index.py`.",
        "",
        "Start here:",
        "",
        "- `backtest_locked_strategy.py` — historical runner; required data/model artifacts are not public",
        "- `audit_strategy_snooping.py` — the anti-snooping audit that killed the strategy (gate D2)",
        "- `audit_execution_realism.py` — historical invalid execution audit; descriptive output only",
        "- `build_btc_5m_episode_dataset.py` — guarded source-time counterfactual builder; not causal/live-achievable",
        "",
    ]
    for heading in order:
        paths = grouped.get(heading)
        if not paths:
            continue
        lines += [f"## {heading}", "", "| Script | Purpose |", "|---|---|"]
        for path in paths:
            lines.append(f"| `{path.name}` | {summary(path)} |")
        lines.append("")

    (ROOT / "tools" / "README.md").write_text("\n".join(lines), encoding="utf-8")


def write_research_index() -> None:
    lines = [
        "# Research scripts (earlier phases)",
        "",
        "These are the scripts from the supervised-modelling phases, kept for",
        "provenance rather than reuse. They ran from the repository root and expect",
        "datasets that are not distributed (see `docs/DATA_AVAILABILITY.md`), so treat",
        "them as a record of what was done, not as a maintained interface.",
        "",
        "The maintained tooling lives in [`tools/`](../tools/README.md).",
        "",
    ]
    total = 0
    for key, (heading, blurb) in RESEARCH_DIRS.items():
        directory = ROOT / "research" / key
        if not directory.is_dir():
            continue
        paths = sorted(directory.glob("*.py"))
        total += len(paths)
        lines += [f"## {heading} (`{key}/`, {len(paths)})", "", blurb, "", "| Script | Purpose |", "|---|---|"]
        for path in paths:
            lines.append(f"| `{path.name}` | {summary(path)} |")
        lines.append("")
    lines.insert(7, f"{total} scripts in total.\n")
    (ROOT / "research" / "README.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    write_tools_index()
    write_research_index()
    print("wrote tools/README.md and research/README.md")
